version: '3.8'

services:
  snapstyle:
    build: .
    container_name: snapstyle_app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads
