"""
SnapStyle FAISS Similarity Search Module
Maintains an in-memory and persisted FAISS IndexFlatIP (Inner Product) index for exact cosine similarity
over 512-dimensional normalized visual feature vectors generated by Transformers CLIP.
- Generates and persists 512-dimensional normalized embeddings for product catalog images.
- Stores embeddings and FAISS index on disk (npz / faiss index files) for instant loading.
- Normalizes all vectors to unit sphere (L2 norm = 1.0) so Inner Product == Cosine Similarity.
- Performs category-filtered visual similarity search with real cosine similarity scores (no fake offsets).
- Returns honest similarity scores, match percentages, and search metadata.
"""

import os
import numpy as np
from typing import List, Dict, Any, Optional

try:
    import faiss
    FAISS_AVAILABLE = True
except ImportError:
    FAISS_AVAILABLE = False

# Default file paths for persisting catalog embeddings and FAISS index
BASE_DIR = os.path.dirname(__file__)
PROJECT_ROOT = os.path.dirname(BASE_DIR)
DEFAULT_STORAGE_DIR = os.path.join(PROJECT_ROOT, "data")
os.makedirs(DEFAULT_STORAGE_DIR, exist_ok=True)

DEFAULT_STORAGE_NPZ = os.path.join(DEFAULT_STORAGE_DIR, "catalog_embeddings.npz")
DEFAULT_INDEX_FILE = os.path.join(DEFAULT_STORAGE_DIR, "catalog.faiss_index")


def normalize_vector(v: np.ndarray) -> np.ndarray:
    """
    Normalizes a feature vector to unit length (L2 norm = 1.0).
    Ensures float32 data type. When vectors have norm 1.0,
    FAISS IndexFlatIP inner product is mathematically identical to Cosine Similarity.
    """
    arr = np.asarray(v, dtype=np.float32).flatten()
    norm = float(np.linalg.norm(arr))
    if norm > 0:
        arr = arr / norm
    return arr


class FashionSimilarityIndex:
    def __init__(
        self,
        dimension: int = 512,
        storage_path: Optional[str] = None,
        index_path: Optional[str] = None
    ):
        self.dimension = dimension
        self.storage_path = storage_path or DEFAULT_STORAGE_NPZ
        self.index_path = index_path or DEFAULT_INDEX_FILE
        self.index: Optional[Any] = None
        self.product_ids: List[str] = []
        self.product_categories: List[str] = []
        self.embeddings: List[np.ndarray] = []
        self._init_index()

    def _init_index(self):
        """Initializes an empty FAISS IndexFlatIP for exact cosine similarity search."""
        if FAISS_AVAILABLE:
            self.index = faiss.IndexFlatIP(self.dimension)
        else:
            self.index = None

    def clear(self):
        """Clears in-memory index, product IDs, categories, and embeddings."""
        self._init_index()
        self.product_ids = []
        self.product_categories = []
        self.embeddings = []

    def is_real_faiss(self) -> bool:
        """Returns True if the FAISS library is available and the real index has items."""
        return FAISS_AVAILABLE and self.index is not None and self.index.ntotal > 0

    def add_product(self, product_id: str, category: str, embedding: np.ndarray):
        """
        Adds a single product to the index.
        Normalizes vector to L2 norm = 1.0 before indexing.
        """
        vec = normalize_vector(embedding).reshape(1, self.dimension)
        
        self.product_ids.append(product_id)
        self.product_categories.append(category.lower())
        self.embeddings.append(vec.flatten())

        if self.index is not None:
            self.index.add(vec)

    def save_to_disk(self, storage_path: Optional[str] = None, index_path: Optional[str] = None) -> bool:
        """
        Persists product embeddings matrix, IDs, and categories to compressed npz,
        and saves the binary FAISS IndexFlatIP index to disk.
        """
        target_npz = storage_path or self.storage_path
        target_idx = index_path or self.index_path

        if not self.product_ids or len(self.embeddings) == 0:
            return False

        try:
            os.makedirs(os.path.dirname(target_npz), exist_ok=True)
            emb_matrix = np.vstack(self.embeddings).astype(np.float32)
            np.savez_compressed(
                target_npz,
                embeddings=emb_matrix,
                product_ids=np.array(self.product_ids, dtype=str),
                product_categories=np.array(self.product_categories, dtype=str),
                dimension=self.dimension
            )

            if FAISS_AVAILABLE and self.index is not None and self.index.ntotal > 0:
                os.makedirs(os.path.dirname(target_idx), exist_ok=True)
                faiss.write_index(self.index, target_idx)

            print(f"[SnapStyle FAISS] Successfully persisted {len(self.product_ids)} catalog embeddings to {target_npz}")
            return True
        except Exception as e:
            print(f"[SnapStyle FAISS] Notice: Error saving embeddings to disk: {e}")
            return False

    def load_from_disk(self, storage_path: Optional[str] = None, index_path: Optional[str] = None) -> bool:
        """
        Loads pre-computed product embeddings and restores the FAISS index from disk.
        Returns True if successfully restored, False otherwise.
        """
        target_npz = storage_path or self.storage_path
        target_idx = index_path or self.index_path

        if not os.path.exists(target_npz):
            return False

        try:
            data = np.load(target_npz, allow_pickle=True)
            embeddings = data["embeddings"].astype(np.float32)
            product_ids = [str(x) for x in data["product_ids"]]
            categories = [str(x) for x in data["product_categories"]]

            # Verify dimensions
            if embeddings.shape[1] != self.dimension or len(product_ids) != embeddings.shape[0]:
                print(f"[SnapStyle FAISS] Cache dimension mismatch, rebuilding required.")
                return False

            self.clear()
            self.product_ids = product_ids
            self.product_categories = categories
            self.embeddings = [row for row in embeddings]

            # If binary faiss index exists on disk, load directly; otherwise re-add to IndexFlatIP
            if FAISS_AVAILABLE and target_idx and os.path.exists(target_idx):
                try:
                    self.index = faiss.read_index(target_idx)
                except Exception:
                    self.index = faiss.IndexFlatIP(self.dimension)
                    self.index.add(embeddings)
            elif FAISS_AVAILABLE:
                self.index = faiss.IndexFlatIP(self.dimension)
                self.index.add(embeddings)

            print(f"[SnapStyle FAISS] Loaded {len(self.product_ids)} product embeddings from disk cache: {target_npz}")
            return True
        except Exception as e:
            print(f"[SnapStyle FAISS] Notice: Failed to load embeddings cache: {e}")
            return False

    def build_or_load_catalog_index(
        self,
        products: List[Dict[str, Any]],
        embedding_func,
        force_rebuild: bool = False
    ):
        """
        Builds or loads the FAISS catalog vector index:
        1. If cache exists and force_rebuild is False, loads precomputed real embeddings from disk instantly.
        2. Otherwise, computes real normalized 512-dim CLIP embeddings for all products and saves to disk.
        """
        if not force_rebuild:
            if self.load_from_disk():
                if len(self.product_ids) == len(products):
                    print(f"[SnapStyle FAISS] Catalog FAISS index ready with {self.index.ntotal if self.index else len(self.product_ids)} products.")
                    return

        # Rebuild from catalog product images
        self.clear()
        print(f"[SnapStyle FAISS] Generating real CLIP embeddings for {len(products)} catalog products...")
        for prod in products:
            pid = prod["product_id"]
            cat = prod.get("category", "")
            vec = embedding_func(prod)
            self.add_product(pid, cat, vec)

        self.save_to_disk()
        total = self.index.ntotal if self.index else len(self.product_ids)
        print(f"[SnapStyle FAISS] Successfully indexed {total} fashion products.")

    # Backwards-compatible alias
    build_catalog_index = build_or_load_catalog_index

    def search(
        self,
        query_vector: np.ndarray,
        category_filter: Optional[str] = None,
        top_k: int = 6
    ) -> List[Dict[str, Any]]:
        """
        Performs exact cosine similarity search using normalized vectors and FAISS IndexFlatIP.
        Computes real similarity score = dot(q, p) = cos(theta) (no fake/demo offsets).
        Filters by category if specified.
        Returns list of matched products sorted by similarity score descending.
        """
        q_vec = normalize_vector(query_vector).reshape(1, self.dimension)
        results = []

        is_real = self.is_real_faiss()

        if is_real and self.index is not None:
            # Query FAISS IndexFlatIP (Inner Product = Cosine Similarity for normalized vectors)
            # When category filter is active, search full index to guarantee all category matches are ranked
            if category_filter and category_filter.lower() != "all":
                k_search = self.index.ntotal
            else:
                k_search = min(self.index.ntotal, max(top_k * 5, 20))

            distances, indices = self.index.search(q_vec, k_search)

            for score, idx in zip(distances[0], indices[0]):
                if idx < 0 or idx >= len(self.product_ids):
                    continue
                pid = self.product_ids[idx]
                cat = self.product_categories[idx]

                # Category matching filter: strict exact match to prevent cross-category false comparisons
                if category_filter and category_filter.lower() != "all":
                    cf = category_filter.strip().lower()
                    if cat.strip().lower() != cf:
                        continue

                sim_score = float(score)
                # Real percentage: positive cosine similarity scaled to [0, 100]
                sim_pct = max(0.0, min(100.0, sim_score * 100.0))

                results.append({
                    "product_id": pid,
                    "similarity_score": round(sim_score, 4),
                    "match_pct": f"{int(round(sim_pct))}% Match",
                    "match_number": int(round(sim_pct)),
                    "category": cat,
                    "is_real_similarity": True,
                    "search_source": "real_faiss"
                })

                if len(results) >= top_k:
                    break
        else:
            # Fallback NumPy dot product if FAISS C++ extension is unavailable
            for idx, vec in enumerate(self.embeddings):
                pid = self.product_ids[idx]
                cat = self.product_categories[idx]

                if category_filter and category_filter.lower() != "all":
                    cf = category_filter.strip().lower()
                    if cat.strip().lower() != cf:
                        continue

                score = float(np.dot(q_vec.flatten(), vec))
                sim_pct = max(0.0, min(100.0, score * 100.0))

                results.append({
                    "product_id": pid,
                    "similarity_score": round(score, 4),
                    "match_pct": f"{int(round(sim_pct))}% Match",
                    "match_number": int(round(sim_pct)),
                    "category": cat,
                    "is_real_similarity": False,
                    "search_source": "fallback_numpy"
                })

            results.sort(key=lambda x: x["similarity_score"], reverse=True)
            results = results[:top_k]

        return results

    def get_index_status(self) -> Dict[str, Any]:
        """Returns detailed status information about the active FAISS index."""
        indexed_count = self.index.ntotal if (self.index is not None) else len(self.product_ids)
        is_real = self.is_real_faiss()
        return {
            "indexed_products_count": indexed_count,
            "dimension": self.dimension,
            "index_type": "IndexFlatIP",
            "faiss_available": FAISS_AVAILABLE,
            "is_real_faiss": is_real,
            "search_source": "real_faiss" if is_real else "fallback_numpy",
            "similarity_metric": "Exact Inner Product (Cosine Similarity on Unit Sphere)",
            "storage_path": self.storage_path,
            "has_stored_cache": os.path.exists(self.storage_path)
        }


# Global singleton instance of FashionSimilarityIndex
fashion_index = FashionSimilarityIndex()
